name: spenza
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  internet_connection_checker_plus:
  dio:
  shared_preferences:
  dartz:
  flutter_bloc:
  equatable:
  get_it:
  bloc_concurrency:
  go_router:
  flutter_svg:
  cached_network_image:
  intl:
  easy_localization:
  image_picker:
  flutter_secure_storage:
  carousel_slider:
  smooth_page_indicator:
  firebase_core:
  firebase_crashlytics:
  flutter_staggered_animations:
  flutter_animate:
  animated_text_kit:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/images/temp/

  fonts:
    - family: Zain
      fonts:
        - asset: assets/fonts/Zain-Light.ttf
          weight: 300
        - asset: assets/fonts/Zain-Regular.ttf
          weight: 400
        - asset: assets/fonts/Zain-Bold.ttf
          weight: 700
        - asset: assets/fonts/Zain-ExtraBold.ttf
          weight: 800

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

  # Android Adaptive Icon (for Android 8.0+)
  adaptive_icon_background: "#D46B60"
  adaptive_icon_foreground: "assets/images/app_icon.png"

  # iOS specific settings
  remove_alpha_ios: true