// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQzVMoX2iZMxJ2qP-N12xravLIY523jkw',
    appId: '1:773812918253:web:76a6fd0de806772bb579e4',
    messagingSenderId: '773812918253',
    projectId: 'spenza-app-95ce1',
    authDomain: 'spenza-app-95ce1.firebaseapp.com',
    storageBucket: 'spenza-app-95ce1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjFb12SiCAce-wJXre2OstLc4ywZ-OJ_I',
    appId: '1:773812918253:android:4c43f0cfbfa91cb0b579e4',
    messagingSenderId: '773812918253',
    projectId: 'spenza-app-95ce1',
    storageBucket: 'spenza-app-95ce1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwePqAq4uovdbiZzEUms2BitkS-V5Uoq0',
    appId: '1:773812918253:ios:1304a9fc9b2556b2b579e4',
    messagingSenderId: '773812918253',
    projectId: 'spenza-app-95ce1',
    storageBucket: 'spenza-app-95ce1.firebasestorage.app',
    iosBundleId: 'com.spenza.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwePqAq4uovdbiZzEUms2BitkS-V5Uoq0',
    appId: '1:773812918253:ios:1304a9fc9b2556b2b579e4',
    messagingSenderId: '773812918253',
    projectId: 'spenza-app-95ce1',
    storageBucket: 'spenza-app-95ce1.firebasestorage.app',
    iosBundleId: 'com.spenza.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQzVMoX2iZMxJ2qP-N12xravLIY523jkw',
    appId: '1:773812918253:web:1d2526162732f434b579e4',
    messagingSenderId: '773812918253',
    projectId: 'spenza-app-95ce1',
    authDomain: 'spenza-app-95ce1.firebaseapp.com',
    storageBucket: 'spenza-app-95ce1.firebasestorage.app',
  );
}
